name: build
on:
  push:
  pull_request:
jobs:
  esp-idf-build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.2
    steps:
      - uses: actions/checkout@v4
      - name: Set target
        run: idf.py set-target esp32
      - name: Build
        run: idf.py build
