name: Build

on:
  push:
    branches: [ "feat/m5stickc-plus2-dualbuild" ]
  pull_request:
    branches: [ "feat/m5stickc-plus2-dualbuild" ]

jobs:
  build-platformio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: |
          pip install -U platformio
      - name: Build ESP32 DevKit
        run: |
          cd platformio
          pio run -e esp32dev || true
      - name: Build M5StickC Plus 2
        run: |
          cd platformio
          pio run -e m5stickc_plus2 || true

name: build
on:
  push:
  pull_request:
jobs:
  esp-idf-build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.2
    steps:
      - uses: actions/checkout@v4
      - name: Set target
        run: idf.py set-target esp32
      - name: Build
        run: idf.py build
